### ISSUE TITLE
Add `ec-gpu` support

### ISSUE THREAD

**Issue by str4d** [zcash/pasta_curves#22]
We want to be able to leverage GPUs in `halo2`, via the [`ec-gpu` crate](https://github.com/filecoin-project/ec-gpu). This requires two changes:

- The curve implementation needs to support producing the GPU kernel for finite field arithmetic.
- `halo2` needs to use GPU-aware MSM and FFT algorithms.

This issue covers the first change. We should implement the `GpuField` trait from the `ec-gpu` crate (behind a `gpu` feature flag), and then the `ec-gpu-gen` crate should be able to generate the necessary CUDA/OpenCL source code.

**Comment by dignifiedquire** [comment]
For reference, this is the trait implementation in `blstrs`
- https://github.com/filecoin-project/blstrs/blob/master/src/lib.rs#L98-L102
- https://github.com/filecoin-project/blstrs/blob/master/src/fp.rs#L659-L672
- https://github.com/filecoin-project/blstrs/blob/master/src/scalar.rs#L613-L626

**Comment by dignifiedquire** [comment]
Note: currently the MSM and FFT implementations are still in `bellperson`, `ec-gpu-gen` just contains the generic curve & field operations.

**Comment by str4d** [comment]
Closed by #31.
