### ISSUE TITLE
Add `alloc` feature flag

### ISSUE THREAD

**Issue by str4d** [zcash/pasta_curves#25]
In #4 we introduced a `std` feature flag, to enable downstream users to disable anything relying on `std`. This happened to gate all of the traits, because both `FieldExt` and `CurveAffine` depended on `std::io`.

We removed `std::io` usage from `FieldExt` in #20, so it could now be removed from any feature flag. `CurveAffine` still relies on `std::io`, but I want to remove that as well. Then we're just left with the fact that `CurveExt` requires `FieldExt`, `FieldExt` is bound on `SqrtRatio`, and the only way we can implement `SqrtRatio` right now depends on `SqrtTables`, which requires `alloc`.

So, we should add an `alloc` feature flag, and move everything behind it. We might also be able to remove the `std` feature flag as a result (which has not been in a release yet). There's no point in having the traits themselves be no-std accessible if we can't implement them without `alloc`. Once we have a fallback for `SqrtRatio` we can consider making the other traits no-std usable.

**Comment by jarys** [comment]
Another reason, why `CurveExt` cannot be accessible without `alloc`, is that `hash_to_curve` still depends on `Box`.

However I would like to be able to compile the crate without sqrt tables to safe memory of our tiny device. I remind you that these tables are only optimization. We already can calculate square roots via Tonelli-Shanks algorithm without tables. 'SqrtRatio` can be  implemented generically as

```rust
fn sqrt_ratio(num: &Self, div: &Self) -> (Choice, Self) {
    //generic implementation:

    //invert div
    let div_inv = (*div).invert().unwrap_or(Self::zero());

    let x = (*num) * div_inv; // x = num/div
    let y = x * Self::root_of_unity(); // y = lambda*num/div

    let x_sqrt = x.sqrt();
    let y_sqrt = y.sqrt();

    // Either x is square or y is square
    let normal_sqrt = CtOption::conditional_select(&y_sqrt, &x_sqrt, x_sqrt.is_some());
    let special_sqrt = CtOption::new(Self::zero(), 1.into());
    let result_sqrt = CtOption::conditional_select(&normal_sqrt, &special_sqrt, div.is_zero());

    let normal_bool = x_sqrt.is_some();
    let special_bool = !div.is_zero();
    let result_bool = Choice::conditional_select(&normal_bool, &special_bool, div.is_zero());

    (result_bool, result_sqrt.unwrap())
}
```

or a little bit more efficiently by separating first part of Tonelli-Shanks algorithm (where the squareness of an input is checked).

May we create a new feature flag to conditionally disable these tables?

**Comment by str4d** [comment]
Hmm, that's a good point about separating the table impl from `alloc`. Yeah, I think it would be fine to have a `sqrt-table` flag that depends on `alloc` to provide them. We can workshop the API beyond that later.
